# Generated by Django 4.1.7 on 2023-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website", "0002_delete_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockWithVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                ("video_iframe_src_url_1", models.URLField()),
                ("video_iframe_src_url_2", models.URLField()),
                ("video_iframe_src_url_3", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("address_1", models.CharField(max_length=255)),
                ("address_2", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("facebook", models.URLField()),
                ("instagram", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content_1", models.CharField(max_length=255)),
                ("content_2", models.CharField(max_length=255)),
                ("content_3", models.CharField(max_length=255)),
                ("content_4", models.CharField(max_length=255)),
                ("price", models.IntegerField(verbose_name="cena")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trainers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                ("profile_url", models.URLField(verbose_name="instagram")),
                ("photo", models.ImageField(upload_to="trainers")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
