# Generated by Django 4.1.7 on 2023-04-27 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockwithvideo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blockwithvideo",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać?",
                verbose_name="aktywne?",
            ),
        ),
        migrations.AddField(
            model_name="blockwithvideo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contactdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactdata",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać?",
                verbose_name="aktywne?",
            ),
        ),
        migrations.AddField(
            model_name="contactdata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offer",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać?",
                verbose_name="aktywne?",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="trainers",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainers",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać?",
                verbose_name="aktywne?",
            ),
        ),
        migrations.AddField(
            model_name="trainers",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
