# Generated by Django 4.1.7 on 2023-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_blockwithvideo_created_at_blockwithvideo_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Czy to ma się wyświetlać?",
                        verbose_name="aktywne?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_1", models.CharField(max_length=255)),
                ("content_2", models.CharField(max_length=255)),
                ("content_3", models.CharField(max_length=255)),
                ("content_4", models.CharField(max_length=255)),
                ("price", models.IntegerField(verbose_name="cena")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="content_1",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="content_2",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="content_3",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="content_4",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="price",
        ),
    ]
