# Generated by Django 4.1.7 on 2023-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_offer_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelist",
            name="price",
            field=models.FloatField(verbose_name="cena"),
        ),
    ]
