# Generated by Django 4.1.7 on 2023-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_pricelist_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockwithvideo",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać na stronie?",
                verbose_name="aktywne?",
            ),
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać na stronie?",
                verbose_name="aktywne?",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać na stronie?",
                verbose_name="aktywne?",
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać na stronie?",
                verbose_name="aktywne?",
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Czy to ma się wyświetlać na stronie?",
                verbose_name="aktywne?",
            ),
        ),
    ]
