# Generated by Django 4.1.7 on 2023-04-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_blockwithvideo_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
