# Generated by Django 4.1.7 on 2023-04-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_trainer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(upload_to='trainers'),
        ),
    ]
