# Generated by Django 4.1.7 on 2023-05-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Czy to ma się wyświetlać na stronie?', verbose_name='aktywne?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructor', models.CharField(max_length=255)),
                ('week_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_item', to='website.weekday')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
