# Generated by Django 4.1.7 on 2023-05-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_scheduleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='is_active',
        ),
    ]
