# Generated by Django 4.1.7 on 2023-05-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_weekday_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='updated_at',
        ),
    ]
