# Generated by Django 4.1.7 on 2023-05-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_weekday_created_at_weekday_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='profile_url',
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='week_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.weekday'),
        ),
    ]
