# Generated by Django 4.1.7 on 2023-05-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_rename_title_blockwithvideo_title1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blockwithvideo",
            old_name="title1",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="contactdata",
            old_name="title1",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="title1",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="pricelist",
            old_name="title1",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="scheduleitem",
            old_name="title1",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="trainer",
            old_name="title1",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="weekday",
            old_name="title1",
            new_name="title",
        ),
    ]
