# Generated by Django 4.1.7 on 2023-06-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_headercontent_alter_scheduleitem_options'),
        ('website', '0020_rename_title1_blockwithvideo_title_and_more'),
    ]

    operations = [
    ]
