# Generated by Django 4.1.7 on 2023-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_merge_20230605_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='youtube',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
