# Generated by Django 4.1.7 on 2023-06-24 10:52

from django.db import migrations


def price_change(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Price = apps.get_model('website', 'PriceList')
    for price in Price.objects.all():
        price.price = str(price.price).split(".0")[0]

        price.save()

def reverse(_x, _y):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_contactdata_youtube_alter_pricelist_price'),
    ]

    operations = [
                migrations.RunPython(price_change, reverse),

    ]
