# Generated by Django 4.1.7 on 2023-06-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20230624_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockwithvideo',
            name='button',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blockwithvideo',
            name='content_button',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
