# Generated by Django 4.1.7 on 2023-06-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_blockwithvideo_button_blockwithvideo_content_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockwithvideo',
            name='content_button',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
