# Generated by Django 4.1.7 on 2023-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_blockwithvideo_content_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockwithvideo',
            name='video_iframe_src_url_4',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockwithvideo',
            name='video_iframe_src_url_5',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
