# Generated by Django 4.1.7 on 2023-07-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0027_remove_blockwithvideo_video_iframe_src_url_5"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Imię")),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Numer telefonu"),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("Strip Dance", "Strip Dance"),
                            ("High Heels", "High Heels"),
                            ("Strip Acro", "Strip Acro"),
                            ("Female Dance", "Female Dance"),
                        ],
                        max_length=255,
                        verbose_name="Rodzaj zajęć",
                    ),
                ),
            ],
        ),
    ]
