# Generated by Django 4.1.7 on 2023-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0029_client_created_at_client_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="consent",
            field=models.BooleanField(
                default=False,
                verbose_name=" Wyrażam zgodę na przetwarzanie moich danych osobowych zgodnie z <a href=''>Polityką prywatności",
            ),
            preserve_default=False,
        ),
    ]
