# Generated by Django 4.1.7 on 2023-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0030_client_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="activity",
            field=models.CharField(
                choices=[
                    (None, "Wybierz"),
                    ("Strip Dance", "Strip Dance"),
                    ("High Heels", "High Heels"),
                    ("Strip Acro", "Strip Acro"),
                    ("Female Dance", "Female Dance"),
                ],
                max_length=255,
                verbose_name="Rodzaj zajęć",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="consent",
            field=models.BooleanField(verbose_name="Zgoda na przetwarzanie danych"),
        ),
    ]
